version: '3'

services:
  django-db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PasswordSQL


  app:
    image: docker-django:latest
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on: 
      - django-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_HOST: django-db

volumes:
  db: